### PR TITLE
Сервер для обработки POST запроса от клиента

### PR DESCRIPTION
**Pull request by Vanish404**
Рабочая болванка, которая обрабатывает с помощью xmlhttprequest запрос от клиента.

### CODE REVIEW

**Comment by irnc** [comment]
@Vanish404 What issue is solved by this pull request?

**Comment by Vanish404** [comment]
@irnc [this](https://github.com/pub-t/plain-destination/issues/11)

**Comment by irnc** [comment]
@Vanish404 Please create separate project for this server prototype, as it has a separate life cycle.

**Comment by Vanish404** [comment]
@irnc Done, [this project](https://github.com/pub-t/plain-destination-server)

**Pull request closed without merging**
