### PR TITLE
Lint CSS files on precommit 

### PR DESCRIPTION
**Pull request by AlexeyKorkoza**
I added csslint script in package.json. 
I have two questions:
1. How do make that csslint script check a css code using described rules which have in a .csslintrc file ?
2. How do make that csslint script check a css code when I make to commit?

### CODE REVIEW

**Comment by KrivichaninDenis** [comment]
where [file](https://github.com/pub-t/plain-destination/pull/41/commits/9d3cdc8f844c6981fbec092414066eac18a38aec#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7) with rules?

**Comment by AlexeyKorkoza** [comment]
I write in scripts next way: "csslint": "csslint .csslintrc .", but csslint check on the default rules.

**Comment by KrivichaninDenis** [comment]
GLTM

**Comment by Vanish404** [comment]
Looks good

**Comment by DemyanchikVadim** [comment]
good

**Pull request merged**
